### DISCUSSION TITLE
Llama-3.3-70B-Instruct-4bit LoRA Fine-Tuning: No Change (or Instability) - Adapter Issue?

### DISCUSSION THREAD

**Discussion by corozcop1980** [ml-explore/mlx-examples#1147] [Q&A] [answered]
Hi everyone,
I’m very new to this and still learning the ropes. I'm struggling to fine-tune mlx-community/Llama-3.3-70B-Instruct-4bit using LoRA (mlx_lm.lora V0.21.0) . The model either doesn't change the output at all (scale=1.0) or becomes completely unstable with gibberish output and NaN/inf values in the logits when I increase the scale even slightly.

The core problem is that the LoRA adapter seems to be having no usable effect on the model's output, despite successful training (loss decreases normally). It's not a matter of fine-tuning the scale - it's like the adaptation either does nothing or breaks the model.

Here's what I've tried:

- Multiple rank and alpha values: I've experimented with rank values of 16, 32, and 64, and alpha values of 4, 8, 16, and 32.
- Different scale values during inference:
  - scale=1.0: No style change whatsoever. The output is identical to the base model.
  - scale=1.5: Model outputs only "?"
  - scale slightly above 1.9355 (with a previous training run): Gibberish output, NaN/inf in logits.
  - scale=4.0 and scale=10 (with a previous training run): Gibberish/repeating tokens, numerical instability.
- Debugging:
  - I've verified that the LoRA weights are loaded correctly from the adapter file (adapters.safetensors).
  - I've confirmed that the scale parameter is correctly passed to the LoRALinear layers during inference.
  - I've checked that the LoRA computations (matrix multiplications) are happening without shape errors during the forward pass.
  - I've inspected the lora_a and lora_b matrices and the z values (LoRA contribution) in LoRALinear.__call__. The z values have a very small standard deviation, suggesting the LoRA modifications are extremely subtle.
  - [DEBUG] LoRA computation - z_std: 0.078338, scale: 4.0, final_std: 0.265381 [DEBUG] Generated logits - mean: inf, std: inf
- Training Results:
  - Training loss decreases steadily and reaches around 1.0, indicating the model is learning something.
  - Initial loss: ~4.8 Final loss: ~1.0-1.2
- Here's my latest training config:

```
model: "mlx-community/Llama-3.3-70B-Instruct-4bit"
train: true
fine_tune_type: "lora"
data: "dataset"
batch_size: 8 
iters: 1000 
learning_rate: 1e-5
lora_parameters:
  keys: ["self_attn.q_proj", "self_attn.v_proj", "self_attn.k_proj", "self_attn.o_proj", "mlp.gate_proj", "mlp.up_proj", "mlp.down_proj"]
  rank: 32 
  alpha: 8
  scale: 1.0 # During training
  dropout: 0.1
lr_schedule:
  name: "cosine_decay"
  warmup: 50
  arguments: [1e-5, 1000, 1e-7]
```
I'm really stuck here, and any insights or suggestions would be greatly appreciated!
