### ISSUE TITLE
load_custom_hf_dataset not handling the text_feature argument properly

### ISSUE THREAD

**Issue by chimezie** [ml-explore/mlx-examples#1087]
If you use a hf_dataset configuration such as (for e.x.)

```yaml
hf_dataset:
  name: "Open-Orca/OpenOrca"
  train_split: "train[:90%]"
  valid_split: "train[-10%:]"
  text_feature: "response"
```

It is supposed to work the same as the (local) text data format, but it comes up against:

```python
        if prompt_feature and completion_feature:
            return CompletionsDataset(ds, tokenizer, prompt_feature, completion_feature)
        elif text_feature:
            return Dataset(train_ds, text_key=text_feature)
        else:
            raise ValueError(
                "Specify either a prompt and completion feature or a text "
                "feature for the Hugging Face dataset."
            )
```

which errors out because `train_ds` is not defined
