### ISSUE TITLE
Computing scale parameter from alpha and rank, if missing

### ISSUE THREAD

**Issue by ivanfioravanti** [ml-explore/mlx-examples#1186]
There are many resources on internet that are still using old config parameters for model training with MLX.
An example [Fine-tuning Phi-3 with Apple MLX Framework](https://github.com/microsoft/Phi-3CookBook/blob/main/md/04.Fine-tuning/FineTuning_MLX.md#note-1) that is still specifying alpha:

```
# LoRA parameters can only be specified in a config file
lora_parameters:
  # The layer keys to apply LoRA to.
  # These will be applied for the last lora_layers
  keys: ["o_proj","qkv_proj"]
  rank: 64
  alpha: 64
  dropout: 0.1
```

I was going to create a PR for them with updated version. But I thought: "What if we compute **scale** dynamically starting from r and alpha? At the end is scale = alpha / rank, right? @awni what do you think? 
Happy to implement this in case, otherwise I will send the PR to Microsoft.
